Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -47,10 +47,18 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
         run: |
-          npx semantic-release --dry-run || true
-          VERSION=$(npx semantic-release --dry-run | grep -oP '(?<=The next release version is )\S+')
-          echo "$VERSION" > .next_version
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          set +e  # Allow the script to continue even if semantic-release exits with code 1
+          VERSION=$(npx semantic-release --dry-run || true)
+          
+          # Check if a version was actually calculated
+          if [[ $VERSION == *"The next release version is"* ]]; then
+            VERSION=$(echo "$VERSION" | grep -oP '(?<=The next release version is )\S+')
+            echo "$VERSION" > .next_version
+            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "No new version to release."
+          fi
+          set -e  # Re-enable exit on error for the rest of the script
 
       - name: Set up GitHub Packages repository
         run: echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
